# Generated by Django 2.2.11 on 2020-04-22 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='unlikes',
        ),
    ]
